service:
  name: lamp-wedding

custom:
  apiGateway:
    binaryMediaTypes:
      - image/png
      - image/jpeg
      - font/woff
      - font/woff2
      - font/ttf
      - "*/*" # Using */* doesn't have side effects that I can tell. The HTML response works fine.
  customDomain:
    domainName: dev.lamp.wedding
    certificateArn: arn:aws:acm:us-east-1:984077873871:certificate/b0189c40-fed4-474f-82fd-689a8290f2cf
#    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: false
    endpointType: edge
#  hooks:
#    before:package:createDeploymentArtifacts:
#      - yarn run build-prod
#  s3Sync:
#  - bucketName: dev.lamp.wedding
#    localDir: dist/frontend
#    acl: public-read

plugins:
  - serverless-offline
#  - serverless-hooks-plugin
#  - serverless-s3-sync
  - serverless-webpack
  - serverless-aws-static-file-handler/plugins/BinaryMediaTypes
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:BatchWriteItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:eu-west-2:*:*

resources:
  Resources:
    guestsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: lamp.wedding.guests
        AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        KeySchema:
        - AttributeName: id
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  serveStatic:
    handler: server.serveStatic
    events:
      - http:
          method: get
          path: /assets/{proxy+}
      - http:
          method: get
          path: /
      - http:
          method: get
          path: /{proxy+}
  putGuests:
    handler: server.guestsPutAll
    events:
    - http:
        cors: true
        method: put
        path: guests
  logView:
    handler: server.logView
    events:
    - http:
        cors: true
        method: put
        path: view
  sendTestEmail:
    handler: server.sendTestEmail
    events:
    - http:
        method: post
        path: email/test
  sendSaveTheDate:
    handler: server.sendSaveTheDate
    events:
    - http:
        method: post
        path: email/save-the-date
  sendSaveTheDate2:
    handler: server.sendSaveTheDate2
    events:
    - http:
        method: post
        path: email/save-the-date-2
