service:
  name: lamp-wedding

plugins:
  - serverless-hooks-plugin
  - serverless-s3-sync

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2

custom:
  hooks:
    before:package:createDeploymentArtifacts:
      - yarn run build-prod
  s3Sync:
    - bucketName: lamp.wedding
      localDir: dist/frontend
      acl: public-read
